# Generated by Django 3.2.3 on 2021-06-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('idp', models.AutoField(primary_key=True, serialize=False)),
                ('comanda', models.IntegerField()),
                ('produto', models.IntegerField()),
                ('qtd', models.IntegerField()),
                ('vendedor', models.CharField(max_length=12, null=True)),
                ('status', models.IntegerField()),
                ('janela', models.IntegerField()),
                ('registro', models.DateTimeField()),
                ('valorund', models.FloatField()),
            ],
            options={
                'db_table': 'comanda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_grupo', models.CharField(blank=True, max_length=45, null=True)),
                ('descr', models.CharField(blank=True, max_length=255, null=True)),
                ('visivel', models.IntegerField()),
            ],
            options={
                'db_table': 'grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=32, null=True)),
                ('colaborador', models.CharField(max_length=12, null=True)),
                ('datahora', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('idprodutos', models.AutoField(primary_key=True, serialize=False)),
                ('nomeoriginal', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('nomefantasia', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('valororiginal', models.FloatField(blank=True, null=True)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('disponibilidade', models.IntegerField(blank=True, null=True)),
                ('federal', models.FloatField(blank=True, null=True)),
                ('estadual', models.FloatField(blank=True, null=True)),
                ('icms', models.FloatField(blank=True, null=True)),
                ('confins', models.FloatField(blank=True, null=True)),
                ('bonus', models.FloatField(blank=True, null=True)),
                ('auxinvst', models.FloatField(blank=True, null=True)),
                ('reserva', models.FloatField(blank=True, null=True)),
                ('regional', models.FloatField(blank=True, null=True)),
                ('descr', models.TextField(blank=True, null=True)),
                ('alergia', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'produtos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=32)),
                ('dataregistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
