# Generated by Django 3.2.15 on 2022-09-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navegador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('login', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('passweb', models.CharField(max_length=17)),
                ('pessoa', models.IntegerField()),
                ('funcao', models.IntegerField()),
                ('sbase', models.FloatField()),
                ('status', models.IntegerField()),
                ('dias_escala', models.IntegerField()),
                ('horas_escala', models.FloatField()),
            ],
            options={
                'db_table': 'colaborador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('primaria', models.IntegerField(primary_key=True, serialize=False)),
                ('pedido', models.IntegerField()),
                ('valorpago', models.IntegerField()),
                ('bandeira', models.CharField(max_length=29)),
                ('registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pagamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Relatorio_e_s_p',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datahora', models.DateTimeField()),
                ('cliente', models.CharField(max_length=32, null=True)),
                ('vendedor', models.CharField(max_length=12, null=True)),
                ('produto', models.IntegerField()),
                ('comanda', models.IntegerField()),
                ('pedido', models.IntegerField()),
                ('disp_anterior', models.IntegerField()),
                ('disp_atual', models.IntegerField()),
                ('obs', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'relatorio_e_s_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_empresa', models.CharField(max_length=45, null=True)),
                ('nome_fantasia', models.CharField(max_length=245, null=True)),
                ('cnpj', models.CharField(max_length=14, null=True)),
                ('inicio_registro', models.DateField()),
                ('fim_registro', models.DateField()),
                ('keycpf_responsavel', models.CharField(max_length=32, null=True)),
                ('maquinas', models.IntegerField()),
                ('chave_registro', models.CharField(max_length=245, null=True)),
                ('tema', models.IntegerField()),
                ('ender', models.CharField(max_length=255, null=True)),
                ('complemento', models.CharField(max_length=255, null=True)),
                ('complemento2', models.CharField(max_length=115, null=True)),
                ('telefone1', models.CharField(max_length=15, null=True)),
                ('telefone2', models.CharField(max_length=15, null=True)),
            ],
            options={
                'db_table': 'tema',
                'managed': False,
            },
        ),
    ]
